pipeline{
    agent any
    stages{ 
        stage('Build'){
            steps{
                echo 'Building the application'
            }
        }
        stage('Testing'){
            steps{
                echo "Testing the application"
            }
        }
        stage('Deploying'){
            steps{
                echo 'Deploying the application!!'
            }
        }
    }
}